[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
