//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cabinet")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: i64,
    pub name: Option<String>,
    pub description: Option<String>,
    pub password: Option<String>,
    pub used: bool,
    pub pending_destruction: bool,
    pub create_at: DateTime,
    pub update_at: DateTime,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
